version: "2"
services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/go-app
    container_name: meu-go-app
    ports:
      - 8080:8080
    environment:
      - ENV=prod
